apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-app
  template:
    metadata:
      labels:
        app: container-app
    spec:
      containers:
      - name: container-app
        image: <your-registry>.azurecr.io/your-app:latest
        ports:
        - containerPort: 80